language: python
python:
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "nightly" # currently points to 3.6-dev
  - "pypy3"
# command to install dependencies
install: "python setup.py install"
# command to run tests
script: py.test
